### ISSUE TITLE
LastSeen is nil with deviceList

### ISSUE THREAD

**Issue by arigon** [TheThingsNetwork/go-app-sdk#17]
Hello

when requesting the devices as a list, the attribute LastSeen is nil. When using Get() to retrieve the device details it is correct.

Code (without error handling and defer):
```
client := config.NewClient(appID, appAccessKey)
devices, _ := client.ManageDevices()
deviceList, _ := devices.List(20, 0)
for _, dev := range deviceList {
	if dev.DevID == "b30fa2b5-edd3-4c4f-aa4e-a3c725016468" {
		fmt.Println(dev.AsDevice().LastSeen)
	}
}

dev, _ := devices.Get("b30fa2b5-edd3-4c4f-aa4e-a3c725016468")
fmt.Println(dev.LastSeen)
```
Output:
```
0001-01-01 00:00:00 +0000 UTC
2020-10-09 20:07:25.73306538 +0200 CEST
```

**Comment by htdvisser** [comment]
I don't think we'll change this anymore, as most of our efforts now go to https://github.com/TheThingsNetwork/lorawan-stack (our v3 stack), and we only work on critical (security) fixes for v2.

**Comment by htdvisser** [comment]
With The Things Network V2 shut down, we're going to archive this repository. This issue will be locked.
