### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by philmcp** [TheThingsNetwork/go-app-sdk#8]
When running `go get github.com/TheThingsNetwork/go-app-sdk` I am getting the following error:

`../../github.com/TheThingsNetwork/api/protocol/lorawan/message_conversion.go:57:26: cannot use cmd.MACCommand() (type lorawan.MACCommand) as type lorawan.Payload in append:`

Any ideas?

**Comment by johanstokking** [comment]
Smells like a vendor issue.

**Comment by htdvisser** [comment]
I updated the vendor files and README, so that you can now use `dep` or `vgo` to get the right versions of all dependencies. @philmcp could you check if this works for you?

**Comment by philmcp** [comment]
Thanks but not quite sure I understand the dep part @htdvisser. I installed dep (`brew install dep`) and ran `go get github.com/TheThingsNetwork/go-app-sdk` again but I still get the same error.

Someone else told me to run `go get -u -d -v github.com/TheThingsNetwork/go-app-sdk` which seemed to work (getting other errors, but not related to the go get part I dont think)

**Comment by philmcp** [comment]
Thanks but not quite sure I understand the dep part @htdvisser. I installed dep (`brew install dep`) and ran `go get -u github.com/golang/dep/cmd/dep` then `cd my-project-path` then `dep ensure`. When I `go build` I get the same error ` cannot use cmd.MACCommand()`. I then tried `go get github.com/TheThingsNetwork/go-app-sdk` but still having the same issue. Maybe Ive misunderstood dep?...

Someone else told me to run `go get -u -d -v github.com/TheThingsNetwork/go-app-sdk` which seemed to work (getting other errors, but not related to the go get part I dont think)

**Comment by johanstokking** [comment]
You should be running `dep ensure` in the `$GOPATH/src/github.com/TheThingsNetwork/go-app-sdk` folder, see the instructions.

**Comment by htdvisser** [comment]
That's indeed strange. With the `vgo` method it seems to work every time, but with `dep` I also get errors on some environments. Could you let me know if the `vgo` method works for you?

I removed the instructions for `dep` until we can reliably fix the build with dep.

**Comment by philmcp** [comment]
Thanks @htdvisser using vgo builds
