### ISSUE TITLE
vendored types

### ISSUE THREAD

**Issue by NeuralSpaz** [TheThingsNetwork/go-app-sdk#9]
Probably should not vendor types that are returned from functions/used in interfaces etc, as it makes it this package impossible to use as intended. If they must be vendored there should be a way for the user to create the type that wraps the vendored type without side effects.

So that people do not get errors like this:
```cannot use u (type *"github.com/TheThingsNetwork/go-app-sdk/vendor/github.com/TheThingsNetwork/ttn/core/types".UplinkMessage) as type *"github.com/TheThingsNetwork/ttn/core/types".UplinkMessage)```

same applies to other types vendored from ttn/core/types that are required to use this pkg: DeviceEvent, Activation, DownlinkMessage,  NwkSKey, AppSKey, DevAddr,AppEUI and DevEUI.

**Comment by htdvisser** [comment]
This should be solved now that we use ttn/core/types as a go module
